/**
 * Папка podbor — лендинг подбора майнинг-отеля.
 * Barrel подпакета.
 */
export * from './mining-hotel'
export {
  PODBOR_MINING_HOTEL_BANNERS_EN,
  PODBOR_MINING_HOTEL_CTA_EN,
  PODBOR_MINING_HOTEL_HOW_WE_WORK_EN,
  PODBOR_MINING_HOTEL_KEY_FACTORS_EN,
  PODBOR_MINING_HOTEL_OFFER_EN,
  PODBOR_MINING_HOTEL_PAGE_EN,
  PODBOR_MINING_HOTEL_PARTNERS_EN,
  PODBOR_MINING_HOTEL_PLACEMENT_EN,
  PODBOR_MINING_HOTEL_SALE_EN,
  PODBOR_MINING_HOTEL_SECURITY_EN,
  PODBOR_MINING_HOTEL_SUMMARY_EN,
  PODBOR_MINING_HOTEL_TIME_SAVE_EN,
  PODBOR_MINING_HOTEL_USEFUL_EN,
} from './mining-hotel-en'
