import type { CatalogResponse } from '~/types/catalog'

export const CATALOG_FALLBACK: CatalogResponse = {
  source: 'fallback',
  updatedAt: new Date().toISOString(),
  meta: {
    totalReviews: 4569,
    subtitle:
      'Помогаем найти подходящую вам компанию и проанализировать конкурентов',
  },
  categories: [
    {
      id: 1,
      name: 'Продажа ASIC',
      slug: 'asic-sales',
      href: '/asic-manufacturers/?category=asic-sales',
      organizations: [
        {
          id: 1,
          name: 'TTM Mining',
          slug: 'ttm-mining',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2026/05/firmennyj-znak-czvetnoj.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/sale_asic/ttm-mining/',
          foundedYear: 2024,
          officeCity: 'Москва',
          hasPublicRating: false,
          verification: {
            contracts: true,
            legalEntity: false,
          },
          cardTags: [
            'Состояние: Новое и БУ',
            'Объем продаж: Розница; ОПТ',
            'Наличие: В наличии и под заказ',
          ],
          cardFeatures: [
            'Доставка по России и миру',
            'Bitmain, Whatsminer, IceRiver, Jasminer',
            'ASIC-майнеры в наличии',
            'Гибкие условия оплаты',
          ],
        },
        {
          id: 2,
          name: 'Geometria',
          slug: 'geometria',
          logoUrl: '/images/catalog/geometria.png',
          rating: 4.5,
          reviewCount: 2,
          href: '/sale_asic/geometria/',
          foundedYear: 2024,
          minAsicPlacement: 5,
          hasPublicRating: true,
          verification: {
            contracts: true,
            legalEntity: true,
          },
          cardTags: [
            'Счет на оплату: С НДС',
            'Состояние: Новое',
            'Объем продаж: ОПТ; Розница от 5 шт.',
            'Наличие: В наличии и под заказ',
          ],
          cardFeatures: [
            'Напрямую от производителей',
            'Официальный импорт с НДС',
            'При покупке у нас — 0 ₽ за размещение',
          ],
        },
        {
          id: 3,
          name: 'Mining center',
          slug: 'mining-center',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/08/mining-center-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/sale_asic/mining-center/',
          foundedYear: 2017,
          hasPublicRating: false,
          cardTags: [
            'Счет на оплату: Без НДС',
            'Состояние: Новое',
            'Объем продаж: Розница, Опт',
            'Наличие: Наличие на складе, Поставка',
          ],
          cardFeatures: [
            'Оплата в USDT',
            'Рассрочка 50%',
            'Прямые поставки с Китая',
          ],
        },
        {
          id: 4,
          name: 'Algoritm',
          slug: 'algoritm',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/07/algoritm-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/sale_asic/algoritm/',
          foundedYear: 2007,
          officeCity: 'Москва',
          hasPublicRating: false,
          verification: {
            contracts: true,
            legalEntity: true,
          },
          cardTags: [
            'Счет на оплату: С НДС',
            'Состояние: Новые',
            'Объем продаж: Оптом',
            'Наличие: Под заказ',
          ],
          cardFeatures: [
            'Доступна поставка без аванса',
            'Рассрочка под залог BTC',
          ],
        },
        {
          id: 5,
          name: 'r7miner',
          slug: 'r7miner',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/r7miner-1.png',
          rating: 4.9,
          reviewCount: 113,
          href: 'https://top-mining.ru/sale_asic/r7miner/',
          foundedYear: 2017,
          officeCity: 'Москва',
          hasPublicRating: true,
          verification: {
            contracts: true,
            legalEntity: true,
          },
          cardTags: [
            'Счет на оплату: С НДС',
            'Состояние: Новое',
            'Объем продаж: Розница, Опт',
            'Наличие: Под заказ',
          ],
          cardFeatures: [
            'Прямые поставки',
            'Гарантия по договору',
            'Белый ввоз',
          ],
        },
        {
          id: 6,
          name: 'IBMM',
          slug: 'ibmm',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/ibmm-90x90-1.png',
          rating: 4.8,
          reviewCount: 486,
          href: 'https://top-mining.ru/sale_asic/ibmm/',
          foundedYear: 2017,
          hasPublicRating: true,
          verification: {
            contracts: true,
            legalEntity: true,
          },
        },
        {
          id: 7,
          name: 'GIS Mining',
          slug: 'gis-mining',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/07/gis-mining-90x90-1.png',
          rating: 4.8,
          reviewCount: 146,
          href: 'https://top-mining.ru/sale_asic/gis-mining/',
          foundedYear: 2019,
          hasPublicRating: true,
          verification: {
            contracts: true,
            legalEntity: true,
          },
        },
        {
          id: 8,
          name: 'Pushminer',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/09/pushminer-2.png',
          rating: 4.5,
          reviewCount: 265,
          href: 'https://top-mining.ru/sale_asic/pushminer/',
        },
      ],
    },
    {
      id: 2,
      name: 'Майнинг-отели',
      slug: 'mining-hotels',
      href: '/asic-manufacturers/?category=mining-hotels',
      organizations: [
        {
          id: 9,
          name: 'RusHash',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2026/02/image-6345356.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/Mining-hotel/rushash/',
        },
        {
          id: 10,
          name: 'Майнинг отель «Терешково»',
          slug: 'majning-otel-gtes-tereshkovo-moskva',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/12/generated-image-5-1.jpg',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/Mining-hotel/majning-otel-gtes-tereshkovo-moskva/',
          foundedYear: 2017,
          officeCity: 'Москва',
          siteCity: 'Москва',
          minAsicPlacement: 1,
          hasPublicRating: false,
          verification: {
            contracts: true,
            legalEntity: true,
            miningRegistry: true,
          },
          cardTags: [
            'Цена за кВт/ч: 5.3',
            'Мощности площадок: 17 МВт',
          ],
          cardFeatures: [
            'Стратегически защищенный объект',
            'Белый хостинг',
            'Полное сопровождение',
          ],
        },
        {
          id: 11,
          name: '1-MINING',
          slug: '1-mining',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/07/1-mining-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/Mining-hotel/1-mining/',
          foundedYear: 2019,
          officeCity: 'Ленинградская область',
          siteCity: 'Ленинградская обл.',
          minAsicPlacement: 5,
          hasPublicRating: false,
          verification: {
            contracts: true,
            legalEntity: true,
            miningRegistry: true,
          },
          cardTags: [
            'Цена за кВт/ч: от 5 руб с НДС',
            'Мощности площадок: 19 МВт',
          ],
          cardFeatures: [
            '20 мин от СПб',
            'Газовая генерация',
            'От 300 кВт',
          ],
        },
        {
          id: 12,
          name: 'Weltall Energy',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/05/weltall-energy.png',
          rating: 5,
          reviewCount: 4,
          href: 'https://top-mining.ru/Mining-hotel/weltall-energy/',
          foundedYear: 2017,
          minAsicPlacement: 10,
        },
        {
          id: 13,
          name: 'DataCheap',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/09/datacheap-1.png',
          rating: 2.5,
          reviewCount: 203,
          href: 'https://top-mining.ru/Mining-hotel/datacheap/',
        },
        {
          id: 14,
          name: 'AFM Hotel',
          slug: 'afm-hotel',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/09/afm-hotel-1-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/Mining-hotel/afm-hotel/',
          foundedYear: 2018,
          siteCity: 'Москва',
          hasPublicRating: false,
          verification: {
            contracts: true,
            legalEntity: true,
            miningRegistry: true,
          },
          cardTags: [
            'Цена за кВт/ч от 5,8₽ кВт/ч',
            'Мощности площадок: 3.5 МВт',
          ],
        },
        {
          id: 15,
          name: 'BitBird',
          slug: 'bitbird',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/09/bitbird-1-1.png',
          rating: 0,
          reviewCount: 5,
          href: 'https://top-mining.ru/Mining-hotel/bitbird/',
          foundedYear: 2021,
          siteCity: 'г. Липецк',
          hasPublicRating: true,
          verification: {
            contracts: true,
            legalEntity: true,
            miningRegistry: true,
          },
          cardTags: [
            'Цена за кВт/ч: от 5,9₽ кВт/ч',
            'Мощности площадок: 8 МВт',
          ],
        },
        {
          id: 16,
          name: 'WATT MANOR',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/09/watt-manor-1.png',
          rating: 0,
          reviewCount: 14,
          href: 'https://top-mining.ru/Mining-hotel/watt-manor/',
        },
      ],
    },
    {
      id: 3,
      name: 'Производители ASIC',
      slug: 'equipment-manufacturers',
      href: '/asic-manufacturers/',
      organizations: [
        {
          id: 17,
          name: 'SealMiner',
          logoUrl: 'https://top-mining.ru/wp-content/uploads/2025/11/1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/sealminer/',
        },
        {
          id: 18,
          name: 'BITMAIN',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/bitmain-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/bitmain-corporation/',
        },
        {
          id: 19,
          name: 'MicroBT',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/microbt-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/microbt-corporation/',
        },
        {
          id: 20,
          name: 'Canaan',
          slug: 'canaan',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/canaan-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/canaan-corporation/',
          foundedYear: 2013,
          hasPublicRating: false,
          cardTags: ['Количество моделей: 20+'],
        },
        {
          id: 21,
          name: 'IceRiver',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/iceriver-1-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/iceriver-corporation/',
        },
        {
          id: 22,
          name: 'Innosilicon',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/innosilicon-90x90-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/corporation-innosilicon/',
        },
        {
          id: 23,
          name: 'Goldshell',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/goldshell-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/corporation-goldshell/',
        },
        {
          id: 24,
          name: 'Jasminer',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/jasminer-1.png',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/asic-manufacturer/corporation-jasminer/',
        },
      ],
    },
    {
      id: 4,
      name: 'Майнинг-пулы',
      slug: 'mining-pools',
      href: '/asic-manufacturers/?category=mining-pools',
      organizations: [
        {
          id: 25,
          name: 'K8X',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2026/03/avatar.jpg',
          rating: 5,
          reviewCount: 5,
          href: 'https://top-mining.ru/mining-pool/k8x/',
        },
        {
          id: 26,
          name: 'Masspool.io',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2026/02/avatar-only-symbol.jpg',
          rating: 5,
          reviewCount: 7,
          href: 'https://top-mining.ru/mining-pool/masspool/',
        },
        {
          id: 27,
          name: 'ViaBTC',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/05/viabtc.png',
          rating: 3.3,
          reviewCount: 18,
          href: 'https://top-mining.ru/mining-pool/viabtc/',
        },
        {
          id: 28,
          name: 'EMCD pool',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/emcd-pool.png',
          rating: 4.7,
          reviewCount: 66,
          href: 'https://top-mining.ru/mining-pool/emcd/',
        },
        {
          id: 29,
          name: 'F2Pool',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/08/f2pool-1.png',
          rating: 4.5,
          reviewCount: 4,
          href: 'https://top-mining.ru/mining-pool/f2pool/',
        },
        {
          id: 30,
          name: 'Antpool',
          slug: 'antpool',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/05/antpool.png',
          rating: 3.6,
          reviewCount: 5,
          href: 'https://top-mining.ru/mining-pool/antpool/',
          foundedYear: 2015,
          hasPublicRating: true,
          cardTags: [
            'Комиссия пула: 4%',
            'Добываемые монеты: ETH; LTC; ETHW; BCH; DCRN; DASH; CKB; ETC; ZEC; KDA; HNS; DCR; RVN',
          ],
          cardFeatures: ['Мобильное приложение'],
        },
        {
          id: 31,
          name: 'Neopool',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2025/12/logo-neopul.png',
          rating: 5,
          reviewCount: 1,
          href: 'https://top-mining.ru/mining-pool/neopool/',
        },
        {
          id: 32,
          name: 'Poolin',
          logoUrl:
            'https://top-mining.ru/wp-content/uploads/2024/06/poolin.png',
          rating: 3.8,
          reviewCount: 4,
          href: 'https://top-mining.ru/mining-pool/poolin/',
        },
      ],
    },
    {
      id: 5,
      name: 'Криптобиржи',
      slug: 'crypto-exchanges',
      href: '/asic-manufacturers/?category=crypto-exchanges',
      organizations: [
        {
          id: 33,
          name: 'Binance',
          slug: 'binance',
          logoUrl: '/images/catalog/binance.png',
          logoTheme: 'light',
          rating: 4.5,
          reviewCount: 371,
          href: 'https://top-mining.ru/crypto-exchange/binance/',
          foundedYear: 2016,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
          cardPromo: 'Призовой фонд на сумму до 500 000 USDT в форме ваучеров',
          cardTags: ['Верификация: KYC', 'Коэф. ликвидности: 895'],
          cardFeatures: [
            'Спот',
            'Деривативы',
            'Стейкинг',
            'P2P',
            'Русскоязычная поддержка',
            'Поддержка RUB',
          ],
        },
        {
          id: 34,
          name: 'KuCoin',
          slug: 'kucoin',
          logoUrl: '/images/catalog/kucoin.png',
          logoTheme: 'light',
          rating: 3.9,
          reviewCount: 45,
          href: 'https://top-mining.ru/crypto-exchange/kucoin/',
          foundedYear: 2017,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 610'],
        },
        {
          id: 35,
          name: 'Bybit',
          slug: 'bybit',
          logoUrl: '/images/catalog/bybit.png',
          logoTheme: 'light',
          rating: 4.2,
          reviewCount: 88,
          href: 'https://top-mining.ru/crypto-exchange/bybit/',
          foundedYear: 2018,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 520'],
        },
        {
          id: 36,
          name: 'OKX',
          slug: 'okx',
          logoUrl: '/images/catalog/okx.png',
          logoTheme: 'light',
          rating: 4.0,
          reviewCount: 62,
          href: 'https://top-mining.ru/crypto-exchange/okx/',
          foundedYear: 2017,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 480'],
        },
        {
          id: 37,
          name: 'HTX',
          slug: 'htx',
          logoUrl: '/images/catalog/htx.png',
          logoTheme: 'light',
          rating: 3.7,
          reviewCount: 34,
          href: 'https://top-mining.ru/crypto-exchange/htx/',
          foundedYear: 2013,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 390'],
        },
        {
          id: 38,
          name: 'MEXC',
          slug: 'mexc',
          logoUrl: '/images/catalog/mexc.png',
          logoTheme: 'light',
          rating: 3.8,
          reviewCount: 28,
          href: 'https://top-mining.ru/crypto-exchange/mexc/',
          foundedYear: 2018,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 350'],
        },
        {
          id: 39,
          name: 'Gate.io',
          slug: 'gate-io',
          logoUrl: '/images/catalog/gate-io.png',
          logoTheme: 'light',
          rating: 3.6,
          reviewCount: 41,
          href: 'https://top-mining.ru/crypto-exchange/gate-io/',
          foundedYear: 2013,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 410'],
        },
        {
          id: 40,
          name: 'Bitget',
          slug: 'bitget',
          logoUrl: '/images/catalog/bitget.png',
          logoTheme: 'light',
          rating: 4.1,
          reviewCount: 55,
          href: 'https://top-mining.ru/crypto-exchange/bitget/',
          foundedYear: 2018,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 440'],
        },
        {
          id: 41,
          name: 'BingX',
          slug: 'bingx',
          logoUrl: '/images/catalog/bingx.png',
          logoTheme: 'light',
          rating: 3.5,
          reviewCount: 19,
          href: 'https://top-mining.ru/crypto-exchange/bingx/',
          foundedYear: 2018,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 280'],
        },
        {
          id: 42,
          name: 'Cryptomus',
          slug: 'cryptomus',
          logoUrl: '/images/catalog/cryptomus.png',
          logoTheme: 'light',
          rating: 4.3,
          reviewCount: 12,
          href: 'https://top-mining.ru/crypto-exchange/cryptomus/',
          foundedYear: 2022,
          hasPublicRating: true,
          cardTags: ['Коэф. ликвидности: 210'],
        },
      ],
    },
    {
      id: 6,
      name: 'Криптокошельки',
      slug: 'crypto-wallets',
      href: '/asic-manufacturers/?category=crypto-wallets',
      organizations: [
        {
          id: 43,
          name: 'Coinbase Wallet',
          slug: 'coinbase-wallet',
          logoUrl: '/images/catalog/coinbase-wallet.png',
          logoTheme: 'light',
          rating: 2.5,
          reviewCount: 2,
          href: 'https://top-mining.ru/crypto-wallet/coinbase-wallet/',
          foundedYear: 2012,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
        },
        {
          id: 44,
          name: 'Trust Wallet',
          slug: 'trust-wallet',
          logoUrl: '/images/catalog/trust-wallet.png',
          logoTheme: 'light',
          rating: 2.0,
          reviewCount: 23,
          href: 'https://top-mining.ru/crypto-wallet/trust-wallet/',
          foundedYear: 2017,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
        },
        {
          id: 45,
          name: 'Exodus',
          slug: 'exodus',
          logoUrl: '/images/catalog/exodus.png',
          logoTheme: 'light',
          rating: 1.8,
          reviewCount: 19,
          href: 'https://top-mining.ru/crypto-wallet/exodus/',
          foundedYear: 2015,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
          cardTags: [
            'Добываемые монеты: BTC; ETH; SOL; ADA; DOT; XRP; LTC; BCH; DOGE; TRX; AVAX; MATIC; ATOM; XLM; ALGO; FIL; EOS; XTZ; DASH; ZEC; DCR; RVN; CKB; KDA; HNS; ETC; NEAR; APT; SUI; TON; INJ; SEI; TIA; ORDI; STX; RUNE; OSMO; KAVA; ROSE; ONE; HBAR; ICP; FLOW; MINA; EGLD; KSM; WAVES',
          ],
        },
        {
          id: 46,
          name: 'Blockchain Wallet',
          slug: 'blockchain-wallet',
          logoUrl: '/images/catalog/blockchain-wallet.png',
          logoTheme: 'light',
          rating: 4.1,
          reviewCount: 25,
          href: 'https://top-mining.ru/crypto-wallet/blockchain-wallet/',
          foundedYear: 2011,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
          cardTags: ['Добываемые монеты: BTC; BCH'],
        },
        {
          id: 47,
          name: 'MyEtherWallet',
          slug: 'myetherwallet',
          logoUrl: '/images/catalog/myetherwallet.png',
          logoTheme: 'light',
          rating: 3.0,
          reviewCount: 1,
          href: 'https://top-mining.ru/crypto-wallet/myetherwallet/',
          foundedYear: 2019,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
        },
        {
          id: 48,
          name: 'MetaMask',
          slug: 'metamask',
          logoUrl: '/images/catalog/metamask.svg',
          logoTheme: 'light',
          rating: 2.5,
          reviewCount: 42,
          href: 'https://top-mining.ru/crypto-wallet/metamask/',
          foundedYear: 2015,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
          cardFeatures: ['Мобильное приложение', 'Поддержка NFT'],
        },
        {
          id: 49,
          name: 'Enjin Wallet',
          slug: 'enjin-wallet',
          logoUrl: '/images/catalog/enjin-wallet.png',
          logoTheme: 'light',
          rating: 1.9,
          reviewCount: 19,
          href: 'https://top-mining.ru/crypto-wallet/enjin-wallet/',
          foundedYear: 2009,
          hasPublicRating: true,
          verification: { contracts: true, legalEntity: true },
        },
        {
          id: 50,
          name: 'Phantom',
          slug: 'phantom',
          logoUrl: '/images/catalog/phantom.png',
          logoTheme: 'light',
          rating: 0,
          reviewCount: 0,
          href: 'https://top-mining.ru/crypto-wallet/phantom/',
          foundedYear: 2020,
          hasPublicRating: false,
          cardTags: [
            'Добываемые монеты: SOL; ETH; BTC; MATIC; SUI; APT; AVAX; BNB; OP; ARB; BASE; POLYGON; ZKSYNC; STARKNET; LINEA; SCROLL; BLAST; MODE; MANTLE; METIS; BOBA; GNOSIS; CELO; FANTOM; HARMONY; MOONBEAM; MOONRIVER; AURORA; CRONOS; KAVA; EVMOS; CANTO; KLAYTN; OASYS; SHIMMER; IOTA; SEI; INJ; TIA; DYM; STRD; JUNO; OSMO; KUJI; AXL; SAGA; NTRN; TON; NEAR; ALGO; XLM; XRP; ADA; DOT; ATOM; LTC; BCH; DOGE; TRX; FIL; EOS; XTZ; DASH; ZEC; DCR; RVN; CKB; KDA; HNS; ETC; NEAR; ORDI; STX; RUNE; ROSE; ONE; HBAR; ICP; FLOW; MINA; EGLD; KSM; WAVES',
          ],
        },
      ],
    },
  ],
}
