export type CalculatorDeviceKind = 'asic' | 'gpu' | 'cpu'

export type CalculatorHardwareModel = {
  id: string
  name: string
  brand: string
  algorithm: string
  hashrate: number
  hashrateUnit: string
  powerW: number
  slug: string
}

export type CalculatorHardwareBrand = {
  name: string
  models: CalculatorHardwareModel[]
}

export type CalculatorDeviceOption = {
  kind: CalculatorDeviceKind
  label: string
  placeholder: string
}

export const CALCULATOR_DEVICE_OPTIONS: CalculatorDeviceOption[] = [
  {
    kind: 'asic',
    label: 'ASIC',
    placeholder: 'Модель ASIC-майнера',
  },
  {
    kind: 'gpu',
    label: 'GPU',
    placeholder: 'Выберите Модель GPU',
  },
  {
    kind: 'cpu',
    label: 'CPU',
    placeholder: 'Выберите Модель CPU',
  },
]

function model(
  brand: string,
  name: string,
  algorithm: string,
  hashrate: number,
  hashrateUnit: string,
  powerW: number,
  slug: string,
): CalculatorHardwareModel {
  return {
    id: slug,
    name,
    brand,
    algorithm,
    hashrate,
    hashrateUnit,
    powerW,
    slug,
  }
}

/** Seed catalog for the picker (mirrors backend hardware domain + popular models). */
export const CALCULATOR_HARDWARE_BY_KIND: Record<
  CalculatorDeviceKind,
  CalculatorHardwareBrand[]
> = {
  asic: [
    {
      name: 'Microbt Whatsminer',
      models: [
        model(
          'Microbt Whatsminer',
          'Microbt Whatsminer M70 214 TH/s',
          'SHA-256',
          214,
          'TH/s',
          3103,
          'microbt-whatsminer-m70-214-th-s',
        ),
        model(
          'Microbt Whatsminer',
          'Microbt Whatsminer M70 236 TH/s',
          'SHA-256',
          236,
          'TH/s',
          3422,
          'microbt-whatsminer-m70-236-th-s',
        ),
        model(
          'Microbt Whatsminer',
          'Microbt Whatsminer M72 246 TH/s',
          'SHA-256',
          246,
          'TH/s',
          3567,
          'microbt-whatsminer-m72-246-th-s',
        ),
        model(
          'Microbt Whatsminer',
          'MicroBT Whatsminer M60S 186 Th/s',
          'SHA-256',
          186,
          'Th/s',
          3145,
          'microbt-whatsminer-m60s-186-th-s',
        ),
        model(
          'Microbt Whatsminer',
          'Microbt Whatsminer M50S 122 Th/s',
          'SHA-256',
          122,
          'Th/s',
          3180,
          'microbt-whatsminer-m50s-122-th-s',
        ),
      ],
    },
    {
      name: 'Bitmain Antminer',
      models: [
        model(
          'Bitmain Antminer',
          'Bitmain Antminer S21 200 Th/s',
          'SHA-256',
          200,
          'Th/s',
          3500,
          'bitmain-antminer-s21-200-th-s',
        ),
        model(
          'Bitmain Antminer',
          'Bitmain Antminer S21 Pro 245 Th/s',
          'SHA-256',
          245,
          'Th/s',
          3675,
          'bitmain-antminer-s21-pro-245-th-s',
        ),
        model(
          'Bitmain Antminer',
          'Bitmain Antminer T21 190 Th/s',
          'SHA-256',
          190,
          'Th/s',
          3610,
          'bitmain-antminer-t21-190-th-s',
        ),
        model(
          'Bitmain Antminer',
          'Bitmain Antminer S19j Pro 104 Th/s',
          'SHA-256',
          104,
          'Th/s',
          3050,
          'bitmain-antminer-s19j-pro-104-th-s',
        ),
        model(
          'Bitmain Antminer',
          'Bitmain Antminer L9 16000 Mh/s',
          'Scrypt',
          16000,
          'Mh/s',
          3360,
          'bitmain-antminer-l9-16000-mh-s',
        ),
      ],
    },
    {
      name: 'Canaan Avalon',
      models: [
        model(
          'Canaan Avalon',
          'Canaan Avalon A16XP 300 Th/s',
          'SHA-256',
          300,
          'Th/s',
          3850,
          'canaan-avalon-a16xp-300-th-s',
        ),
        model(
          'Canaan Avalon',
          'Canaan Avalon A15 Pro 218T 218 Th/s',
          'SHA-256',
          218,
          'Th/s',
          3662,
          'canaan-avalon-a15-pro-218t-218-th-s',
        ),
        model(
          'Canaan Avalon',
          'Canaan Avalon A1366 130 Th/s',
          'SHA-256',
          130,
          'Th/s',
          3250,
          'canaan-avalon-a1366-130-th-s',
        ),
      ],
    },
    {
      name: 'Goldshell',
      models: [
        model(
          'Goldshell',
          'Goldshell LT6 3350 Mh/s',
          'Scrypt',
          3350,
          'Mh/s',
          3200,
          'goldshell-lt6-3350-mh-s',
        ),
        model(
          'Goldshell',
          'Goldshell Mini Doge 185 Mh/s',
          'Scrypt',
          185,
          'Mh/s',
          235,
          'goldshell-mini-doge-185-mh-s',
        ),
      ],
    },
    {
      name: 'Innosilicon',
      models: [
        model(
          'Innosilicon',
          'Innosilicon T4+ 175 Th/s',
          'SHA-256',
          175,
          'Th/s',
          3120,
          'innosilicon-t4plus-175-th-s',
        ),
        model(
          'Innosilicon',
          'Innosilicon A11 Pro 8GB 2000 Mh/s',
          'Etchash',
          2000,
          'Mh/s',
          2500,
          'innosilicon-a11-pro-8gb-2000-mh-s',
        ),
      ],
    },
    {
      name: 'ipollo',
      models: [
        model(
          'Ipollo',
          'Ipollo B2 110 Th/s',
          'SHA-256',
          110,
          'Th/s',
          3250,
          'ipollo-b2-110-th-s',
        ),
        model(
          'Ipollo',
          'Ipollo V1 Mini 300 Mh/s',
          'Etchash',
          300,
          'Mh/s',
          240,
          'ipollo-v1-mini-300-mh-s',
        ),
      ],
    },
    {
      name: 'Jasminer',
      models: [
        model(
          'Jasminer',
          'Jasminer X16-P 5800 MH/s',
          'Etchash',
          5800,
          'MH/s',
          1900,
          'jasminer-x16-p-5800-mh-s',
        ),
        model(
          'Jasminer',
          'Jasminer X4 2500 Mh/s',
          'Etchash',
          2500,
          'Mh/s',
          1200,
          'jasminer-x4-2500-mh-s',
        ),
      ],
    },
    {
      name: 'BeeMiner',
      models: [
        model(
          'BeeMiner',
          'BeeMiner LD4 5 Gh/s',
          'Scrypt',
          5,
          'Gh/s',
          3550,
          'beeminer-ld4-5-gh-s',
        ),
      ],
    },
    {
      name: 'Hummer',
      models: [
        model(
          'Hummer',
          'Hummer H9 Pro 80 Th/s',
          'SHA-256',
          80,
          'Th/s',
          3360,
          'hummer-h9-pro-80-th-s',
        ),
      ],
    },
    {
      name: 'Elphapex',
      models: [
        model(
          'Elphapex',
          'ElphaPex DG1+ 13000 Mh/s',
          'Scrypt',
          13000,
          'Mh/s',
          3510,
          'elphapex-dg1plus-13000-mh-s',
        ),
        model(
          'Elphapex',
          'ElphaPex DG2 20000 Mh/s',
          'Scrypt',
          20000,
          'Mh/s',
          3800,
          'elphapex-dg2-20000-mh-s',
        ),
      ],
    },
  ],
  gpu: [
    {
      name: 'AMD',
      models: [
        model(
          'AMD',
          'Radeon RX 7900 XTX',
          'Ethash',
          105,
          'Mh/s',
          320,
          'radeon-rx-7900-xtx',
        ),
        model(
          'AMD',
          'Radeon RX 7900 XT',
          'Ethash',
          83,
          'Mh/s',
          300,
          'radeon-rx-7900-xt',
        ),
        model(
          'AMD',
          'Radeon RX 7800 XT',
          'DynexSolve',
          1.55,
          'Mh/s',
          160,
          'radeon-rx-7800-xt',
        ),
        model(
          'AMD',
          'Radeon RX 7700 XT',
          'Autolykos',
          91.58,
          'Mh/s',
          121,
          'radeon-rx-7700-xt',
        ),
        model(
          'AMD',
          'Radeon RX 7600',
          'Etchash',
          322,
          'Mh/s',
          81,
          'radeon-rx-7600',
        ),
        model(
          'AMD',
          'Radeon RX 6950 XT',
          'Ethash',
          53.86,
          'Mh/s',
          136,
          'radeon-rx-6950-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6900 XT',
          'Ethash',
          62,
          'Mh/s',
          150,
          'radeon-rx-6900-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6800 XT',
          'Ethash',
          62,
          'Mh/s',
          110,
          'radeon-rx-6800-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6800',
          'Ethash',
          61,
          'Mh/s',
          110,
          'radeon-rx-6800',
        ),
        model(
          'AMD',
          'Radeon RX 6750 XT',
          'Ethash',
          40.11,
          'Mh/s',
          73,
          'radeon-rx-6750-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6700 XT',
          'Ethash',
          46,
          'Mh/s',
          100,
          'radeon-rx-6700-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6650 XT',
          'Ethash',
          27.37,
          'Mh/s',
          46,
          'radeon-rx-6650-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6600 XT',
          'Ethash',
          32,
          'Mh/s',
          70,
          'radeon-rx-6600-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6600',
          'Ethash',
          28.5,
          'Mh/s',
          60,
          'radeon-rx-6600',
        ),
        model(
          'AMD',
          'Radeon VII',
          'Ethash',
          94,
          'Mh/s',
          180,
          'radeon-vii',
        ),
        model(
          'AMD',
          'Radeon RX 6500 XT',
          'Etchash',
          13.32,
          'Mh/s',
          26,
          'radeon-rx-6500-xt',
        ),
        model(
          'AMD',
          'Radeon RX 6400',
          'Blake3',
          0.26,
          'Mh/s',
          13,
          'radeon-rx-6400',
        ),
        model(
          'AMD',
          'Radeon RX 5700 XT',
          'Ethash',
          55,
          'Mh/s',
          130,
          'radeon-rx-5700-xt',
        ),
        model(
          'AMD',
          'Radeon RX 5700',
          'Ethash',
          55,
          'Mh/s',
          130,
          'radeon-rx-5700',
        ),
        model(
          'AMD',
          'Radeon RX 5600 XT',
          'Ethash',
          40.5,
          'Mh/s',
          110,
          'radeon-rx-5600-xt',
        ),
        model(
          'AMD',
          'Radeon RX 5500 XT 8GB',
          'Ethash',
          26,
          'Mh/s',
          90,
          'radeon-rx-5500-xt-8gb',
        ),
        model(
          'AMD',
          'Radeon RX Vega 64',
          'Ethash',
          50,
          'Mh/s',
          180,
          'radeon-rx-vega-64',
        ),
        model(
          'AMD',
          'Radeon RX Vega 56',
          'Ethash',
          49,
          'Mh/s',
          170,
          'radeon-rx-vega-56',
        ),
        model(
          'AMD',
          'Radeon RX 590',
          'KawPow',
          10.94,
          'Mh/s',
          104,
          'radeon-rx-590',
        ),
        model(
          'AMD',
          'Radeon RX 580 8GB',
          'Ethash',
          30.5,
          'Mh/s',
          130,
          'radeon-rx-580-8gb',
        ),
        model(
          'AMD',
          'Radeon RX 570 8GB',
          'Ethash4G',
          27.9,
          'Mh/s',
          120,
          'radeon-rx-570-8gb',
        ),
        model(
          'AMD',
          'Radeon RX 570 4GB',
          'Zhash',
          19,
          'Mh/s',
          100,
          'radeon-rx-570-4gb',
        ),
        model(
          'AMD',
          'Radeon RX 480 8GB',
          'Ethash',
          30,
          'Mh/s',
          140,
          'radeon-rx-480-8gb',
        ),
        model(
          'AMD',
          'Radeon RX 470 4GB',
          'Ethash4G',
          26,
          'Mh/s',
          120,
          'radeon-rx-470-4gb',
        ),
        model(
          'AMD',
          'Radeon R9 Fury',
          'Ethash4G',
          29,
          'Mh/s',
          220,
          'radeon-r9-fury',
        ),
        model(
          'AMD',
          'Radeon R9 380 4GB',
          'Ethash4G',
          19,
          'Mh/s',
          150,
          'radeon-r9-380-4gb',
        ),
      ],
    },
    {
      name: 'NVIDIA',
      models: [
        model(
          'NVIDIA',
          'GeForce RTX 4090',
          'Ethash',
          127,
          'Mh/s',
          260,
          'geforce-rtx-4090',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4080',
          'Ethash',
          87,
          'Mh/s',
          200,
          'geforce-rtx-4080',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4070 Ti Super',
          'Ethash',
          83,
          'Mh/s',
          190,
          'geforce-rtx-4070-ti-super',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4070 Ti',
          'Ethash',
          65,
          'Mh/s',
          120,
          'geforce-rtx-4070-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4070 Super',
          'Ethash',
          63,
          'Mh/s',
          150,
          'geforce-rtx-4070-super',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4070',
          'Ethash',
          62,
          'Mh/s',
          140,
          'geforce-rtx-4070',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4060 Ti',
          'Ethash',
          39,
          'Mh/s',
          80,
          'geforce-rtx-4060-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 4060',
          'Blake3',
          1.18,
          'Mh/s',
          90,
          'geforce-rtx-4060',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3090 Ti',
          'Ethash',
          128,
          'Mh/s',
          350,
          'geforce-rtx-3090-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3090',
          'Ethash',
          119,
          'Mh/s',
          320,
          'geforce-rtx-3090',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3080 Ti',
          'Ethash',
          117,
          'Mh/s',
          330,
          'geforce-rtx-3080-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3080',
          'Ethash',
          98,
          'Mh/s',
          240,
          'geforce-rtx-3080',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3070 Ti',
          'Ethash',
          80,
          'Mh/s',
          200,
          'geforce-rtx-3070-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3070',
          'KawPow',
          30.59,
          'Mh/s',
          150,
          'geforce-rtx-3070',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3070 Ti Laptop',
          'NexaPow',
          77.14,
          'Mh/s',
          123,
          'geforce-rtx-3070-ti-laptop',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3070 Laptop',
          'NexaPow',
          67.11,
          'Mh/s',
          110,
          'geforce-rtx-3070-laptop',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3060 Ti GDDR6X',
          'blake3Ironfish',
          97700,
          'Mh/s',
          68,
          'geforce-rtx-3060-ti-gddr6x',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3060 Ti',
          'Ethash',
          60,
          'Mh/s',
          140,
          'geforce-rtx-3060-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3060',
          'Ethash',
          41,
          'Mh/s',
          110,
          'geforce-rtx-3060',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 3050',
          'Ethash',
          29.69,
          'Mh/s',
          85,
          'geforce-rtx-3050',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2080 Ti',
          'Ethash',
          55.2,
          'Mh/s',
          180,
          'geforce-rtx-2080-ti',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2080 Super',
          'Ethash',
          460,
          'Mh/s',
          160,
          'geforce-rtx-2080-super',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2080',
          'Ethash',
          41,
          'Mh/s',
          160,
          'geforce-rtx-2080',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2070 Super',
          'Ethash',
          44.1,
          'Mh/s',
          109,
          'geforce-rtx-2070-super',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2070',
          'Ethash',
          41,
          'Mh/s',
          140,
          'geforce-rtx-2070',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2060 Super',
          'Ethash',
          43.43,
          'Mh/s',
          105,
          'geforce-rtx-2060-super',
        ),
        model(
          'NVIDIA',
          'GeForce RTX 2060',
          'Ethash',
          31,
          'Mh/s',
          120,
          'geforce-rtx-2060',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1660 Super',
          'Ethash',
          29,
          'Mh/s',
          90,
          'geforce-gtx-1660-super',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1660 Ti',
          'Ethash',
          28,
          'Mh/s',
          80,
          'geforce-gtx-1660-ti',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1660',
          'Ethash',
          24,
          'Mh/s',
          80,
          'geforce-gtx-1660',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1080 Ti',
          'Ethash',
          37.5,
          'Mh/s',
          180,
          'geforce-gtx-1080-ti',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1080',
          'Ethash',
          33.5,
          'Mh/s',
          170,
          'geforce-gtx-1080',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1070 Ti',
          'Ethash',
          28,
          'Mh/s',
          140,
          'geforce-gtx-1070-ti',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1070',
          'Ethash',
          30,
          'Mh/s',
          130,
          'geforce-gtx-1070',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1060 6GB',
          'Ethash',
          20.5,
          'Mh/s',
          90,
          'geforce-gtx-1060-6gb',
        ),
        model(
          'NVIDIA',
          'GeForce GTX 1050 Ti',
          'Ethash4G',
          13,
          'Mh/s',
          80,
          'geforce-gtx-1050-ti',
        ),
        model(
          'NVIDIA',
          'RTX A2000 6GB',
          'Ethash',
          39,
          'Mh/s',
          80,
          'rtx-a2000-6gb',
        ),
        model(
          'NVIDIA',
          'RTX A4000',
          'Ethash',
          59,
          'Mh/s',
          140,
          'rtx-a4000',
        ),
        model(
          'NVIDIA',
          'RTX A4500',
          'Ethash',
          87,
          'Mh/s',
          190,
          'rtx-a4500',
        ),
        model(
          'NVIDIA',
          'RTX A5000',
          'Ethash',
          99,
          'Mh/s',
          230,
          'rtx-a5000',
        ),
        model(
          'NVIDIA',
          'CMP 170HX',
          'Blake3',
          1.53,
          'Mh/s',
          104,
          'cmp-170hx',
        ),
        model(
          'NVIDIA',
          'CMP 30HX',
          'NexaPow',
          32.26,
          'Mh/s',
          75,
          'cmp-30hx',
        ),
        model(
          'NVIDIA',
          'CMP 40HX',
          'NexaPow',
          47.96,
          'Mh/s',
          123,
          'cmp-40hx',
        ),
        model(
          'NVIDIA',
          'CMP 50HX',
          'NexaPow',
          67.69,
          'Mh/s',
          137,
          'cmp-50hx',
        ),
        model(
          'NVIDIA',
          'CMP 70HX',
          'Ethash',
          80.76,
          'Mh/s',
          199,
          'cmp-70hx',
        ),
        model(
          'NVIDIA',
          'CMP 90HX',
          'Ethash',
          100.16,
          'Mh/s',
          249,
          'cmp-90hx',
        ),
        model(
          'NVIDIA',
          'P102-100',
          'Ethash',
          450,
          'Mh/s',
          190,
          'p102-100',
        ),
        model(
          'NVIDIA',
          'P104-100',
          'Ethash',
          36.27,
          'Mh/s',
          135,
          'p104-100',
        ),
        model(
          'NVIDIA',
          'P106-100',
          'Ethash',
          23.36,
          'Mh/s',
          86,
          'p106-100',
        ),
      ],
    },
    {
      name: 'INTEL',
      models: [
        model(
          'INTEL',
          'Arc A750',
          'Etchash',
          50.88,
          'Mh/s',
          165,
          'arc-a750',
        ),
        model(
          'INTEL',
          'Arc A380',
          'Zhash',
          20.2,
          'Mh/s',
          75,
          'arc-a380',
        ),
      ],
    },
  ],
  cpu: [
    {
      name: 'AMD',
      models: [
        model(
          'AMD',
          'Ryzen 9 7950X3D',
          'RandomX',
          22500,
          'H/s',
          120,
          'ryzen-9-7950x3d',
        ),
        model(
          'AMD',
          'Ryzen 9 5950X',
          'RandomX',
          20000,
          'H/s',
          105,
          'ryzen-9-5950x',
        ),
        model(
          'AMD',
          'Ryzen 7 5800X',
          'RandomX',
          11100,
          'H/s',
          105,
          'ryzen-7-5800x',
        ),
        model(
          'AMD',
          'Ryzen 5 5600X',
          'GhostRider',
          2100,
          'H/s',
          65,
          'ryzen-5-5600x',
        ),
        model('AMD', 'EPYC 7763', 'RandomX', 47000, 'H/s', 310, 'epyc-7763'),
      ],
    },
    {
      name: 'INTEL',
      models: [
        model('INTEL', 'i9-13900K', 'RandomX', 13480, 'H/s', 125, 'i9-13900k'),
        model('INTEL', 'i9-12900K', 'RandomX', 11600, 'H/s', 125, 'i9-12900k'),
        model('INTEL', 'i7-10700K', 'RandomX', 5600, 'H/s', 125, 'i7-10700k'),
        model('INTEL', 'i5-10600K', 'RandomX', 5640, 'H/s', 125, 'i5-10600k'),
      ],
    },
  ],
}

export function formatHardwareModelMeta(
  item: CalculatorHardwareModel,
): string {
  return `${item.algorithm} | ${item.hashrate} ${item.hashrateUnit} | ${item.powerW} Вт`
}

export function filterHardwareBrands(
  brands: CalculatorHardwareBrand[],
  query: string,
): CalculatorHardwareBrand[] {
  const normalized = query.trim().toLowerCase()
  if (!normalized) {
    return brands
  }

  return brands
    .map((brand) => {
      const brandMatches = brand.name.toLowerCase().includes(normalized)
      const models = brandMatches
        ? brand.models
        : brand.models.filter(
            (item) =>
              item.name.toLowerCase().includes(normalized) ||
              item.algorithm.toLowerCase().includes(normalized),
          )

      return models.length ? { ...brand, models } : null
    })
    .filter((brand): brand is CalculatorHardwareBrand => Boolean(brand))
}
